import Head from "next/head";
import { useEffect, useState } from "react";
import { fetchcompetitions } from "./api/competition";

export default function Home() {
  const [competition, setcompetition] = useState([]);

  useEffect(() => {
    fetchcompetitions().then((data) => {
      setcompetition(data);
    });
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
